--- #YAML:1.0
name:                AI-ParticleSwarmOptimization
version:             1.003
abstract:            OO Perl implementation of Particle Swarm Optimization
license:             perl
author:              
    - Peter Jaquiery (grandpa@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Math::Random::MT:              0
    Test::Pod:                     0
    Test::Pod::Coverage:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
